___

<a href='https://mp.weixin.qq.com/mp/appmsgalbum?__biz=Mzg2OTU4NzI3NQ==&action=getalbum&album_id=1764511202329624577&scene=126#wechat_redirect'> <img src=../../../../pic/project_logo.jpg></a>
___

# NumPy 索引&筛选

我们将讨论如何从数组中选择元素或元素组。

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 中括号 Bracket Indexing and Selection

选择数组的一个或一些元素的最简单的方法就是下面这样，类似于 python 列表。

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

## 广播 Broadcasting

Numpy 数组不同于普通的 Python 列表，它们能够广播：

In [7]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

注意更改也发生在原始数组中！

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

数据没有被复制，它是原始数组的视图！这样可以避免内存问题！

In [12]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## 索引二维数组（矩阵）

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_2d[1]

array([20, 25, 30])

In [15]:
arr_2d[1][0] #第二行第一列

20

In [16]:
arr_2d[1,0] #第二行第一列

20

In [17]:
#Shape (2,2) 右上角
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
arr_2d[2]

array([35, 40, 45])

In [19]:
arr_2d[2,:]

array([35, 40, 45])

### 花式索引

花式索引允许无序选择整个行或列，为了显示这一点，再构建一个 numpy 数组

In [20]:
arr2d = np.zeros((10,10))

In [23]:
arr_length = arr2d.shape[1]

In [24]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [25]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [26]:
# 任何顺序
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## 筛选

In [27]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr = arr>4

In [30]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
