___

<a href='https://mp.weixin.qq.com/mp/appmsgalbum?__biz=Mzg2OTU4NzI3NQ==&action=getalbum&album_id=1764511202329624577&scene=126#wechat_redirect'> <img src=../../../../pic/project_logo.jpg></a>
___

# NumPy 操作

## 算术

In [2]:
import numpy as np
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [3]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**3

array([  1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## 通用数组函数 Universal Array Functions

Numpy 带有许多[通用函数](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)，它们本质上是数学运算，可以对整个数组使用函数，进行计算。

In [9]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [10]:
np.max(arr) #same as arr.max()

9

In [11]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [14]:
np.log2(arr)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

# Great Job!